#!/usr/bin/bash

sudo yum install -y git \
                    gcc \
                    autoconf \
                    automake \
                    libcurl-devel \
                    openssl-devel \
                    json-c-devel \
                    pam-devel \
                    libtool \
                    rpm-build \
                    libtool-ltdl-devel

#sudo yum install git
#sudo yum install gcc
#sudo yum install autoconf automake
#sudo yum install libcurl-devel
#sudo yum install libssl-devel
#sudo yum install openssl-devel
#sudo yum install json-c-devel
#sudo yum install pam-devel
#sudo  yum install libtool
#sudo yum install rpm-build
#sudo yum install libtool-ltdl-devel


autoreconf -i
#CFLAGS="-Wall -O0 -ggdb3" PKG_CONFIG_PATH=/usr/local/cmocka-1.1.1/lib/pkgconfig/ ./configure
./configure
make dist

mkdir -p tmp/
( cd tmp ; \
  mkdir -p BUILD BUILDROOT RPMS SOURCES SPECS SRPMS; \
  cp ../globus_ssh-*.tar.gz SOURCES; \
  echo "%_topdir " `pwd` >> ~/.rpmmacros; \
  #rpmbuild -v -bb --noclean  ../packaging/fedora/globus-ssh.spec; \
  rpmbuild -v -bb --clean  ../packaging/fedora/globus-ssh.spec; \
)
